;;; -*- lisp -*-

(in-package :conskivi-fileonly-tests)

(def-test pubsub-subscribe-publish (:suite pubsub-operations)
  (with-fixture test-database ()
    (let ((received nil))
      (conskivi-subscribe db :channel1 (lambda (msg) (push msg received)))
      (conskivi-publish db :channel1 "hello")
      (conskivi-publish db :channel1 "world")
      (sleep 0.1)
      (is (equal received '("world" "hello"))))))

(def-test pubsub-unsubscribe (:suite pubsub-operations)
  (with-fixture test-database ()
    (let ((received nil))
      (conskivi-subscribe db :channel1 (lambda (msg) (push msg received)))
      (conskivi-publish db :channel1 "hello")
      (sleep 0.1)
      (conskivi-unsubscribe db :channel1)
      (conskivi-publish db :channel1 "world")
      (sleep 0.1)
      (is (equal received '("hello"))))))

(def-test pubsub-multiple-subscribers (:suite pubsub-operations)
  (with-fixture test-database ()
    (let ((received1 nil)
          (received2 nil))
      (conskivi-subscribe db :channel1 (lambda (msg) (push msg received1)))
      (conskivi-subscribe db :channel1 (lambda (msg) (push msg received2)))
      (conskivi-publish db :channel1 "hello")
      (sleep 0.1)
      (is (equal received1 '("hello")))
      (is (equal received2 '("hello"))))))

(def-test pubsub-psubscribe (:suite pubsub-operations)
  (with-fixture test-database ()
    (let ((received nil))
      (conskivi-psubscribe db "CHANNEL.*" (lambda (msg) (push msg received)))
      (conskivi-publish db :channel1 "hello")
      (conskivi-publish db :channel2 "world")
      (sleep 0.1)
      (is (equal received '("world" "hello"))))))

(def-test pubsub-punsubscribe (:suite pubsub-operations)
  (with-fixture test-database ()
    (let ((received nil))
      (conskivi-psubscribe db "CHANNEL.*" (lambda (msg) (push msg received)))
      (conskivi-publish db :channel1 "hello")
      (sleep 0.1)
      (conskivi-punsubscribe db "CHANNEL.*")
      (conskivi-publish db :channel2 "world")
      (sleep 0.1)
      (is (equal received '("hello"))))))