;;; -*- lisp -*-

(in-package :conskivi-fileonly-tests)

(def-test set-sadd (:suite set-operations)
  (with-fixture test-database ()
    (let ((added (conskivi-sadd db :key1 "a" "b" "c")))
      (is (= added 3))
      (is (= (conskivi-scard db :key1) 3)))))

(def-test set-sadd-duplicate (:suite set-operations)
  (with-fixture test-database ()
    (conskivi-sadd db :key1 "a" "b")
    (let ((added (conskivi-sadd db :key1 "b" "c")))
      (is (= added 1))
      (is (= (conskivi-scard db :key1) 3)))))

(def-test set-srem (:suite set-operations)
  (with-fixture test-database ()
    (conskivi-sadd db :key1 "a" "b" "c")
    (let ((removed (conskivi-srem db :key1 "b")))
      (is (= removed 1))
      (is (= (conskivi-scard db :key1) 2)))))

(def-test set-smembers (:suite set-operations)
  (with-fixture test-database ()
    (conskivi-sadd db :key1 "a" "b" "c")
    (let ((members (conskivi-smembers db :key1)))
      (is (= (length members) 3))
      (is (member "a" members :test #'equal))
      (is (member "b" members :test #'equal))
      (is (member "c" members :test #'equal)))))

(def-test set-sismember (:suite set-operations)
  (with-fixture test-database ()
    (conskivi-sadd db :key1 "a" "b" "c")
    (is (conskivi-sismember db :key1 "a"))
    (is (not (conskivi-sismember db :key1 "d")))))

(def-test set-scard (:suite set-operations)
  (with-fixture test-database ()
    (conskivi-sadd db :key1 "a" "b" "c")
    (is (= (conskivi-scard db :key1) 3))
    (is (= (conskivi-scard db :nonexistent) 0))))

(def-test set-sunion (:suite set-operations)
  (with-fixture test-database ()
    (conskivi-sadd db :key1 "a" "b")
    (conskivi-sadd db :key2 "b" "c")
    (let ((union (conskivi-sunion db (list :key1 :key2))))
      (is (= (length union) 3))
      (is (member "a" union :test #'equal))
      (is (member "b" union :test #'equal))
      (is (member "c" union :test #'equal)))))

(def-test set-sinter (:suite set-operations)
  (with-fixture test-database ()
    (conskivi-sadd db :key1 "a" "b")
    (conskivi-sadd db :key2 "b" "c")
    (let ((inter (conskivi-sinter db (list :key1 :key2))))
      (is (= (length inter) 1))
      (is (member "b" inter :test #'equal)))))

(def-test set-sdiff (:suite set-operations)
  (with-fixture test-database ()
    (conskivi-sadd db :key1 "a" "b")
    (conskivi-sadd db :key2 "b" "c")
    (let ((diff (conskivi-sdiff db (list :key1 :key2))))
      (is (= (length diff) 1))
      (is (member "a" diff :test #'equal)))))

(def-test set-sscan (:suite set-operations)
  (with-fixture test-database ()
    (iter (for i from 1 to 10)
      (conskivi-sadd db :key1 (format nil "member~a" i)))
    (let ((result (conskivi-sscan db :key1 nil nil 3)))
      (is (= (length (first result)) 3))
      (is (second result)))))