;;; -*- lisp -*-

(in-package :conskivi-fileonly-tests)

(def-test transaction-multi-exec (:suite transaction-operations)
  (with-fixture test-database ()
    (conskivi-multi db)
    (conskivi-put db :key1 "value1")
    (conskivi-put db :key2 "value2")
    (conskivi-exec db)
    (is (equal (conskivi-get db :key1) "value1"))
    (is (equal (conskivi-get db :key2) "value2"))))

(def-test transaction-discard (:suite transaction-operations)
  (with-fixture test-database ()
    (conskivi-multi db)
    (conskivi-put db :key1 "value1")
    (conskivi-discard db)
    (is (null (conskivi-get db :key1)))))

(def-test transaction-watch (:suite transaction-operations)
  (with-fixture test-database ()
    (conskivi-put db :key1 "initial")
    (conskivi-watch db :key1)
    (conskivi-multi db)
    (conskivi-put db :key1 "modified")
    (conskivi-exec db)
    (is (equal (conskivi-get db :key1) "modified"))))

(def-test transaction-watch-modified (:suite transaction-operations)
  (with-fixture test-database ()
    (conskivi-put db :key1 "initial")
    (conskivi-watch db :key1)
    (conskivi-put db :key1 "modified-by-other")
    (conskivi-multi db)
    (conskivi-put db :key1 "modified-by-transaction")
    (signals error (conskivi-exec db))))

(def-test transaction-unwatch (:suite transaction-operations)
  (with-fixture test-database ()
    (conskivi-put db :key1 "initial")
    (conskivi-watch db :key1)
    (conskivi-unwatch db)
    (conskivi-put db :key1 "modified")
    (conskivi-multi db)
    (conskivi-put db :key1 "final")
    (conskivi-exec db)
    (is (equal (conskivi-get db :key1) "final"))))

(def-test transaction-empty (:suite transaction-operations)
  (with-fixture test-database ()
    (conskivi-multi db)
    (let ((result (conskivi-exec db)))
      (is (null result)))))