;;; -*- lisp -*-

(in-package #:conskivi-fileonly)

;;; Hash table helper

(defun hash-table-keys (ht)
  (let ((keys nil))
    (maphash (lambda (k v) (declare (ignore v)) (push k keys)) ht)
    keys))

;;; Type tags for binary encoding

(defconstant +type-nil+     0)
(defconstant +type-string+  1)
(defconstant +type-integer+ 2)
(defconstant +type-float+   3)
(defconstant +type-boolean+ 4)
(defconstant +type-keyword+ 5)
(defconstant +type-list+    6)
(defconstant +type-hash+    7)
(defconstant +type-zset+    8)
(defconstant +type-array+   9)

;;; Binary write helpers

(defun write-u8 (stream value)
  (write-byte (logand value #xFF) stream))

(defun write-u32 (stream value)
  (write-byte (logand value #xFF) stream)
  (write-byte (logand (ash value -8) #xFF) stream)
  (write-byte (logand (ash value -16) #xFF) stream)
  (write-byte (logand (ash value -24) #xFF) stream))

(defun write-i64 (stream value)
  (let ((bytes (make-array 8 :element-type '(unsigned-byte 8))))
    (dotimes (i 8)
      (setf (aref bytes i) (logand value #xFF))
      (setf value (ash value -8)))
    (write-sequence bytes stream)))

(defun write-double (stream value)
  (let ((bits (ieee-floats:encode-float64 (coerce value 'double-float))))
    (write-i64 stream bits)))

(defun write-bytes (stream bytes)
  (write-u32 stream (length bytes))
  (write-sequence bytes stream))

(defun write-utf8 (stream string)
  (let ((bytes (flexi-streams:string-to-octets string :external-format :utf-8)))
    (write-bytes stream bytes)))

;;; Binary read helpers

(defun read-u8 (stream)
  (read-byte stream))

(defun read-u32 (stream)
  (let ((value 0))
    (setf (ldb (byte 8 0) value) (read-byte stream))
    (setf (ldb (byte 8 8) value) (read-byte stream))
    (setf (ldb (byte 8 16) value) (read-byte stream))
    (setf (ldb (byte 8 24) value) (read-byte stream))
    value))

(defun read-i64 (stream)
  (let ((value 0))
    (dotimes (i 8)
      (setf (ldb (byte 8 (* i 8)) value) (read-byte stream)))
    (when (>= value (ash 1 63))
      (setf value (- value (ash 1 64))))
    value))

(defun read-double (stream)
  (let ((bits (read-i64 stream)))
    (ieee-floats:decode-float64 bits)))

(defun read-bytes (stream)
  (let ((len (read-u32 stream)))
    (let ((bytes (make-array len :element-type '(unsigned-byte 8))))
      (read-sequence bytes stream)
      bytes)))

(defun read-utf8 (stream)
  (let ((bytes (read-bytes stream)))
    (flexi-streams:octets-to-string bytes :external-format :utf-8)))

;;; Value encoding

(defun encode-value-typed (stream value)
  "Encode a value with its type tag (for recursive/nested use)."
  (cond
    ((null value) (write-u8 stream +type-nil+))
    ((stringp value)
     (write-u8 stream +type-string+)
     (write-utf8 stream value))
    ((integerp value)
     (write-u8 stream +type-integer+)
     (write-i64 stream value))
    ((floatp value)
     (write-u8 stream +type-float+)
     (write-double stream (coerce value 'double-float)))
    ((eq value t)
     (write-u8 stream +type-boolean+)
     (write-u8 stream 1))
    ((symbolp value)
     (write-u8 stream +type-keyword+)
     (write-utf8 stream (symbol-name value)))
    ((listp value)
     (write-u8 stream +type-list+)
     (write-u32 stream (length value))
     (dolist (item value)
       (encode-value-typed stream item)))
    ((hash-table-p value)
     (if (gethash :sorted-set value)
         (progn
           (write-u8 stream +type-zset+)
           (let ((scores (gethash :scores value)))
             (write-u32 stream (hash-table-count scores))
             (maphash (lambda (member score)
                        (encode-value-typed stream member)
                        (write-double stream score))
                      scores)))
         (progn
           (write-u8 stream +type-hash+)
           (write-u32 stream (hash-table-count value))
           (maphash (lambda (field field-value)
                      (encode-value-typed stream field)
                      (encode-value-typed stream field-value))
                    value))))
    ((vectorp value)
     (write-u8 stream +type-array+)
     (write-u32 stream (array-rank value))
     (dotimes (i (array-rank value))
       (write-u32 stream (array-dimension value i)))
     (write-u32 stream (array-total-size value))
     (dotimes (i (array-total-size value))
       (encode-value-typed stream (row-major-aref value i))))
    (t
     (write-u8 stream +type-string+)
     (write-utf8 stream (format nil "~a" value)))))

(defun encode-value-data (stream value type)
  "Encode just the value data without a type tag (for top-level file storage)."
  (ecase type
    ((nil) nil)
    (:string (write-utf8 stream value))
    (:integer (write-i64 stream value))
    (:float (write-double stream (coerce value 'double-float)))
    (:boolean (write-u8 stream (if value 1 0)))
    (:keyword (write-utf8 stream (symbol-name value)))
    (:list
     (write-u32 stream (length value))
     (dolist (item value)
       (encode-value-typed stream item)))
    (:hash
     (write-u32 stream (hash-table-count value))
     (maphash (lambda (field field-value)
                (encode-value-typed stream field)
                (encode-value-typed stream field-value))
              value))
    (:sorted-set
     (let ((scores (gethash :scores value)))
       (write-u32 stream (hash-table-count scores))
       (maphash (lambda (member score)
                  (encode-value-typed stream member)
                  (write-double stream score))
                scores)))
    (:array
     (write-u32 stream (array-rank value))
     (dotimes (i (array-rank value))
       (write-u32 stream (array-dimension value i)))
     (write-u32 stream (array-total-size value))
     (dotimes (i (array-total-size value))
       (encode-value-typed stream (row-major-aref value i))))))

;;; Value decoding

(defun decode-value-type (stream)
  (let ((type-tag (read-u8 stream)))
    (ecase type-tag
      (#.+type-nil+     nil)
      (#.+type-string+  (read-utf8 stream))
      (#.+type-integer+ (read-i64 stream))
      (#.+type-float+ (let ((d (read-double stream)))
                      (if (= d (coerce d 'single-float))
                          (coerce d 'single-float)
                          d)))
      (#.+type-boolean+ (= (read-u8 stream) 1))
      (#.+type-keyword+ (intern (read-utf8 stream) :keyword))
      (#.+type-list+    (decode-list stream))
      (#.+type-hash+    (decode-hash stream))
      (#.+type-zset+    (decode-zset stream))
      (#.+type-array+   (decode-array stream)))))

(defun decode-list (stream)
  (let ((count (read-u32 stream)))
    (let ((result (make-list count)))
      (do ((i 0 (1+ i)))
          ((= i count) result)
        (setf (nth i result) (decode-value-type stream))))))

(defun decode-hash (stream)
  (let ((count (read-u32 stream))
        (ht (make-hash-table :test #'equal)))
    (dotimes (i count)
      (let ((field (decode-value-type stream))
            (value (decode-value-type stream)))
        (setf (gethash field ht) value)))
    ht))

(defun decode-zset (stream)
  (let ((count (read-u32 stream))
        (scores (make-hash-table :test #'equal))
        (members (make-hash-table :test #'equal)))
    (dotimes (i count)
      (let* ((member (decode-value-type stream))
             (score-d (read-double stream))
             (score (if (= score-d (coerce score-d 'single-float))
                        (coerce score-d 'single-float)
                        score-d)))
        (setf (gethash member scores) score)
        (setf (gethash member members) t)))
    (let ((ht (make-hash-table :test #'equal)))
      (setf (gethash :sorted-set ht) t)
      (setf (gethash :scores ht) scores)
      (setf (gethash :members ht) members)
      ht)))

(defun decode-array (stream)
  (let ((ndims (read-u32 stream)))
    (let ((dims (make-list ndims)))
      (dotimes (i ndims)
        (setf (nth i dims) (read-u32 stream)))
      (let ((total-size (read-u32 stream))
            (result (make-array dims :adjustable nil)))
        (dotimes (i total-size)
          (setf (row-major-aref result i) (decode-value-type stream)))
        result))))

;;; File-level encode/decode (with expiration)

(defun encode-key-data (stream value type expiration)
  (write-u8 stream (ecase type
                     (:string  +type-string+)
                     (:integer +type-integer+)
                     (:float   +type-float+)
                     (:boolean +type-boolean+)
                     (:keyword +type-keyword+)
                     (:list    +type-list+)
                     (:hash    +type-hash+)
                     (:sorted-set +type-zset+)
                     (:array   +type-array+)
                     ((nil)    +type-nil+)))
  (write-i64 stream (or expiration 0))
  (when value
    (encode-value-data stream value type)))

(defun decode-key-data (stream)
  (let ((type-tag (read-u8 stream))
        (expiration (read-i64 stream)))
    (let ((type (ecase type-tag
                  (#.+type-nil+     nil)
                  (#.+type-string+  :string)
                  (#.+type-integer+ :integer)
                  (#.+type-float+   :float)
                  (#.+type-boolean+ :boolean)
                  (#.+type-keyword+ :keyword)
                  (#.+type-list+    :list)
                  (#.+type-hash+    :hash)
                  (#.+type-zset+    :sorted-set)
                  (#.+type-array+   :array))))
      (values (when (/= type-tag +type-nil+)
                (decode-value-type-after-type stream type-tag))
              type
              (when (plusp expiration) expiration)))))

(defun decode-value-type-after-type (stream type-tag)
  (ecase type-tag
    (#.+type-nil+     nil)
    (#.+type-string+  (read-utf8 stream))
    (#.+type-integer+ (read-i64 stream))
    (#.+type-float+ (let ((d (read-double stream)))
                      (if (= d (coerce d 'single-float))
                          (coerce d 'single-float)
                          d)))
    (#.+type-boolean+ (= (read-u8 stream) 1))
    (#.+type-keyword+ (intern (read-utf8 stream) :keyword))
    (#.+type-list+    (decode-list stream))
    (#.+type-hash+    (decode-hash stream))
    (#.+type-zset+    (decode-zset stream))
    (#.+type-array+   (decode-array stream))))

(defun detect-type (value)
  (cond
    ((null value) nil)
    ((stringp value) :string)
    ((integerp value) :integer)
    ((floatp value) :float)
    ((eq value t) :boolean)
    ((symbolp value) :keyword)
    ((listp value) :list)
    ((hash-table-p value)
     (if (gethash :sorted-set value)
         :sorted-set
         :hash))
    ((vectorp value) :array)
    (t :string)))
