;;; -*- lisp -*-

(in-package :conskivi-inmemory-tests)

(def-test hash-hset (:suite hash-operations)
  (with-fixture test-database ()
    (let ((added (conskivi-hset db :key1 "field1" "value1")))
      (is (= added 1))
      (is (equal (conskivi-hget db :key1 "field1") "value1")))))

(def-test hash-hset-multiple (:suite hash-operations)
  (with-fixture test-database ()
    (conskivi-hset db :key1 "field1" "value1")
    (conskivi-hset db :key1 "field2" "value2")
    (is (= (length (conskivi-hkeys db :key1)) 2))))

(def-test hash-hget (:suite hash-operations)
  (with-fixture test-database ()
    (conskivi-hset db :key1 "field1" "value1")
    (is (equal (conskivi-hget db :key1 "field1") "value1"))
    (is (null (conskivi-hget db :key1 "nonexistent")))))

(def-test hash-hdel (:suite hash-operations)
  (with-fixture test-database ()
    (conskivi-hset db :key1 "field1" "value1")
    (conskivi-hset db :key1 "field2" "value2")
    (is (conskivi-hdel db :key1 "field1"))
    (is (not (conskivi-hdel db :key1 "field1")))
    (is (= (length (conskivi-hkeys db :key1)) 1))))

(def-test hash-hgetall (:suite hash-operations)
  (with-fixture test-database ()
    (conskivi-hset db :key1 "field1" "value1")
    (conskivi-hset db :key1 "field2" "value2")
    (let ((all (conskivi-hgetall db :key1)))
      (is (= (length all) 4))
      (is (member "field1" all :test #'equal))
      (is (member "value1" all :test #'equal))
      (is (member "field2" all :test #'equal))
      (is (member "value2" all :test #'equal)))))

(def-test hash-hkeys (:suite hash-operations)
  (with-fixture test-database ()
    (conskivi-hset db :key1 "field1" "value1")
    (conskivi-hset db :key1 "field2" "value2")
    (let ((keys (conskivi-hkeys db :key1)))
      (is (= (length keys) 2))
      (is (member "field1" keys :test #'equal))
      (is (member "field2" keys :test #'equal)))))

(def-test hash-hvals (:suite hash-operations)
  (with-fixture test-database ()
    (conskivi-hset db :key1 "field1" "value1")
    (conskivi-hset db :key1 "field2" "value2")
    (let ((vals (conskivi-hvals db :key1)))
      (is (= (length vals) 2))
      (is (member "value1" vals :test #'equal))
      (is (member "value2" vals :test #'equal)))))

(def-test hash-hexists (:suite hash-operations)
  (with-fixture test-database ()
    (conskivi-hset db :key1 "field1" "value1")
    (is (conskivi-hexists db :key1 "field1"))
    (is (not (conskivi-hexists db :key1 "nonexistent")))))

(def-test hash-hincrby (:suite hash-operations)
  (with-fixture test-database ()
    (conskivi-hset db :key1 "field1" 10)
    (let ((result (conskivi-hincrby db :key1 "field1" 5)))
      (is (= result 15))
      (is (= (conskivi-hget db :key1 "field1") 15)))))

(def-test hash-hscan (:suite hash-operations)
  (with-fixture test-database ()
    (iter (for i from 1 to 10)
      (conskivi-hset db :key1 (format nil "field~a" i) (format nil "value~a" i)))
    (let ((result (conskivi-hscan db :key1 nil nil 3)))
      (is (= (length (first result)) 6))
      (is (second result)))))