;;; -*- lisp -*-

(in-package :conskivi-inmemory-tests)

(def-test key-exists (:suite key-operations)
  (with-fixture test-database ()
    (conskivi-put db :key1 "value1")
    (is (conskivi-exists db :key1))
    (is (not (conskivi-exists db :nonexistent)))))

(def-test key-type (:suite key-operations)
  (with-fixture test-database ()
    (conskivi-put db :key1 "value1")
    (conskivi-put db :key2 42)
    (conskivi-put db :key3 3.14)
    (conskivi-put db :key4 :value)
    (conskivi-put db :key5 t)
    (conskivi-put db :key6 '(1 2 3))
    (conskivi-put db :key7 #(1 2 3))
    (conskivi-put db :key8 (make-hash-table :test #'equal))
    (is (eq (conskivi-type db :key1) :string))
    (is (eq (conskivi-type db :key2) :integer))
    (is (eq (conskivi-type db :key3) :float))
    (is (eq (conskivi-type db :key4) :keyword))
    (is (eq (conskivi-type db :key5) :boolean))
    (is (eq (conskivi-type db :key6) :list))
    (is (eq (conskivi-type db :key7) :array))
    (is (eq (conskivi-type db :key8) :hash))))

(def-test key-type-nonexistent (:suite key-operations)
  (with-fixture test-database ()
    (is (null (conskivi-type db :nonexistent)))))

(def-test key-keys (:suite key-operations)
  (with-fixture test-database ()
    (conskivi-put db :key1 "value1")
    (conskivi-put db :key2 "value2")
    (conskivi-put db :other "value3")
    (let ((keys (conskivi-keys db)))
      (is (= (length keys) 3))
      (is (member :key1 keys))
      (is (member :key2 keys))
      (is (member :other keys)))))

(def-test key-keys-pattern (:suite key-operations)
  (with-fixture test-database ()
    (conskivi-put db :key1 "value1")
    (conskivi-put db :key2 "value2")
    (conskivi-put db :other "value3")
    (let ((keys (conskivi-keys db "KEY.*")))
      (is (= (length keys) 2))
      (is (member :key1 keys))
      (is (member :key2 keys)))))

(def-test key-scan (:suite key-operations)
  (with-fixture test-database ()
    (iter (for i from 1 to 20)
      (conskivi-put db (intern (format nil "KEY~a" i) :keyword) (format nil "value~a" i)))
    (let ((result (conskivi-scan db nil nil 5)))
      (is (= (length (first result)) 5))
      (is (second result)))))

(def-test key-expire-ttl (:suite key-operations)
  (with-fixture test-database ()
    (conskivi-put db :key1 "value1")
    (conskivi-expire db :key1 10)
    (let ((ttl (conskivi-ttl db :key1)))
      (is (>= ttl 0))
      (is (<= ttl 10)))))

(def-test key-expire-persist (:suite key-operations)
  (with-fixture test-database ()
    (conskivi-put db :key1 "value1")
    (conskivi-expire db :key1 10)
    (conskivi-persist db :key1)
    (is (= (conskivi-ttl db :key1) -1))))

(def-test key-ttl-nonexistent (:suite key-operations)
  (with-fixture test-database ()
    (is (= (conskivi-ttl db :nonexistent) -2))))

(def-test key-ttl-no-expiry (:suite key-operations)
  (with-fixture test-database ()
    (conskivi-put db :key1 "value1")
    (is (= (conskivi-ttl db :key1) -1))))