;;; -*- lisp -*-

(in-package :conskivi-inmemory-tests)

(def-test sorted-set-zadd (:suite sorted-set-operations)
  (with-fixture test-database ()
    (let ((added (conskivi-zadd db :key1 1.0 "a")))
      (is (= added 1))
      (is (= (conskivi-zcard db :key1) 1)))))

(def-test sorted-set-zadd-multiple (:suite sorted-set-operations)
  (with-fixture test-database ()
    (let ((added (conskivi-zadd db :key1 1.0 "a" 2.0 "b" 3.0 "c")))
      (is (= added 3))
      (is (= (conskivi-zcard db :key1) 3)))))

(def-test sorted-set-zadd-update (:suite sorted-set-operations)
  (with-fixture test-database ()
    (conskivi-zadd db :key1 1.0 "a")
    (let ((added (conskivi-zadd db :key1 2.0 "a")))
      (is (= added 0))
      (is (= (conskivi-zscore db :key1 "a") 2.0)))))

(def-test sorted-set-zrem (:suite sorted-set-operations)
  (with-fixture test-database ()
    (conskivi-zadd db :key1 1.0 "a" 2.0 "b" 3.0 "c")
    (let ((removed (conskivi-zrem db :key1 "b")))
      (is (= removed 1))
      (is (= (conskivi-zcard db :key1) 2)))))

(def-test sorted-set-zrange (:suite sorted-set-operations)
  (with-fixture test-database ()
    (conskivi-zadd db :key1 1.0 "a" 2.0 "b" 3.0 "c")
    (let ((range (conskivi-zrange db :key1 0 1)))
      (is (equal range '("a" "b"))))))

(def-test sorted-set-zrange-withscores (:suite sorted-set-operations)
  (with-fixture test-database ()
    (conskivi-zadd db :key1 1.0 "a" 2.0 "b" 3.0 "c")
    (let ((range (conskivi-zrange db :key1 0 1 t)))
      (is (equal range '("a" 1.0 "b" 2.0))))))

(def-test sorted-set-zrevrange (:suite sorted-set-operations)
  (with-fixture test-database ()
    (conskivi-zadd db :key1 1.0 "a" 2.0 "b" 3.0 "c")
    (let ((range (conskivi-zrevrange db :key1 0 1)))
      (is (equal range '("c" "b"))))))

(def-test sorted-set-zscore (:suite sorted-set-operations)
  (with-fixture test-database ()
    (conskivi-zadd db :key1 1.0 "a" 2.0 "b")
    (is (= (conskivi-zscore db :key1 "a") 1.0))
    (is (= (conskivi-zscore db :key1 "b") 2.0))))

(def-test sorted-set-zcard (:suite sorted-set-operations)
  (with-fixture test-database ()
    (conskivi-zadd db :key1 1.0 "a" 2.0 "b" 3.0 "c")
    (is (= (conskivi-zcard db :key1) 3))
    (is (= (conskivi-zcard db :nonexistent) 0))))

(def-test sorted-set-zincrby (:suite sorted-set-operations)
  (with-fixture test-database ()
    (conskivi-zadd db :key1 1.0 "a")
    (let ((new-score (conskivi-zincrby db :key1 2.5 "a")))
      (is (= new-score 3.5))
      (is (= (conskivi-zscore db :key1 "a") 3.5)))))

(def-test sorted-set-zscan (:suite sorted-set-operations)
  (with-fixture test-database ()
    (iter (for i from 1 to 10)
      (conskivi-zadd db :key1 (float i) (format nil "member~a" i)))
    (let ((result (conskivi-zscan db :key1 nil nil 3)))
      (is (= (length (first result)) 6))
      (is (second result)))))